### ISSUE TITLE
Build failed in jitpack.io

### ISSUE THREAD

**Issue by JellyBrick** [Marcono1234/lingua#3]
https://jitpack.io/#Marcono1234/tiny-lingua

caused by `buildSrc`

**Comment by Marcono1234** [comment]
Thanks for your interest in this project!

I have updated the project with the latest upstream Lingua changes, and also modified the build script now. However, building on JitPack currently fails with "Max repo size 500MB exceeded", probably because JitPack considers the size of the complete history of the repository, see also https://github.com/jitpack/jitpack.io/issues/5210.
I am not sure if that can be solved in some way (without rewriting the Git history).

Is [manually building](https://github.com/Marcono1234/tiny-lingua?tab=readme-ov-file#building) this project an option for you at the moment?

I have created #5 to track publishing to Maven Central, but I am not sure when or even if I will do that, since there are multiple requirements for publishing to Maven Central.

**Comment by JellyBrick** [comment]
- "Max repo size 500MB exceeded" issue is solved by trying to build with the repository's administrator signed in to jitpack.
- jitpack only supports java 8, so it requires additional configuration to set java 17 to fix the issue. Please see #6 (Successful build log on my fork: https://jitpack.io/com/github/JellyBrick/tiny-lingua/529d9edae1/build.log)

**Comment by Marcono1234** [comment]
Thanks, that has solved it! I am wondering though if in the future it will always be necessary that I am the one triggering the JitPack build if a user wants to use it (this time I triggered the build from the browser), or if just the fact that I logged in with my GitHub account was enough and now all builds will work, regardless of who triggers it.

Also, hopefully you like Tiny Lingua! Feel free to share any feedback 🙂
